-- MySQL Script generated by MySQL Workbench
-- Fri Jan 22 22:26:10 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HOTEL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HOTEL` ;

-- -----------------------------------------------------
-- Schema HOTEL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HOTEL` DEFAULT CHARACTER SET utf8 ;
USE `HOTEL` ;

-- -----------------------------------------------------
-- Table `HOTEL`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL`.`CLIENTS` (
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `CHECK_IN` DATETIME NOT NULL,
  `CHECK_OUT` DATETIME NOT NULL,
  `ROOM_NUMBER` INT NOT NULL,
  PRIMARY KEY (`LAST_NAME`, `FIRST_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL`.`ROOMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL`.`ROOMS` (
  `ROOM_NUMBER` INT NOT NULL,
  `NUMBER_OF_BEDROOMS` VARCHAR(45) NOT NULL,
  `IS_FREE` TINYINT(1) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`ROOM_NUMBER`),
  UNIQUE INDEX `ROOM_NUMBER_UNIQUE` (`ROOM_NUMBER` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL`.`EXCURTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL`.`EXCURTIONS` (
  `idEXCURTIONS` INT NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `PRICE` DECIMAL(11) NULL,
  `DURATION` INT NULL,
  PRIMARY KEY (`idEXCURTIONS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL`.`BOOKED_EXCURTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL`.`BOOKED_EXCURTIONS` (
  `BOOKING_ITEM` INT NOT NULL AUTO_INCREMENT,
  `idEXCURTIONS` INT NOT NULL,
  `CLIENTS_LAST_NAME` VARCHAR(45) NOT NULL,
  `CLIENTS_FIRST_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BOOKING_ITEM`, `idEXCURTIONS`, `CLIENTS_LAST_NAME`, `CLIENTS_FIRST_NAME`),
  INDEX `fk_EXCURTIONS_has_CLIENTS_CLIENTS1_idx` (`CLIENTS_LAST_NAME` ASC, `CLIENTS_FIRST_NAME` ASC),
  INDEX `fk_EXCURTIONS_has_CLIENTS_EXCURTIONS1_idx` (`idEXCURTIONS` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `HOTEL`.`CLIENTS`
-- -----------------------------------------------------
START TRANSACTION;
USE `HOTEL`;
INSERT INTO `HOTEL`.`CLIENTS` (`LAST_NAME`, `FIRST_NAME`, `CHECK_IN`, `CHECK_OUT`, `ROOM_NUMBER`) VALUES ('Solovey', 'Maxim', '07.01.2016', '14.01.2016', 14);

COMMIT;


-- -----------------------------------------------------
-- Data for table `HOTEL`.`ROOMS`
-- -----------------------------------------------------
START TRANSACTION;
USE `HOTEL`;
INSERT INTO `HOTEL`.`ROOMS` (`ROOM_NUMBER`, `NUMBER_OF_BEDROOMS`, `IS_FREE`, `DESCRIPTION`) VALUES (14, '2', false, 'Beautiful sea view');

COMMIT;


-- -----------------------------------------------------
-- Data for table `HOTEL`.`EXCURTIONS`
-- -----------------------------------------------------
START TRANSACTION;
USE `HOTEL`;
INSERT INTO `HOTEL`.`EXCURTIONS` (`idEXCURTIONS`, `DESCRIPTION`, `PRICE`, `DURATION`) VALUES (1, 'local sight-seeing tour', 12, 60);

COMMIT;


-- -----------------------------------------------------
-- Data for table `HOTEL`.`BOOKED_EXCURTIONS`
-- -----------------------------------------------------
START TRANSACTION;
USE `HOTEL`;
INSERT INTO `HOTEL`.`BOOKED_EXCURTIONS` (`BOOKING_ITEM`, `idEXCURTIONS`, `CLIENTS_LAST_NAME`, `CLIENTS_FIRST_NAME`) VALUES (1, 1, 'Solovey', 'Maxim');

COMMIT;

